export const sampleData = JSON.stringify( {
        "environmental": {
            "explanation": "The environmental category includes topics related to the company's impact on the natural environment. This can include issues such as waste management, soil health, and biodiversity. These topics are important for <aaaaaaaaaaaaaaa> as they operate in the <aaaaaaaaaaaaaaa> industry sector. Their activities and products may have significant environmental implications, and addressing these topics can help mitigate negative impacts and promote sustainability.",
            "topics": [
                {
                    "topic": {
                        "name": "Topic 13.8 Waste",
                        "description": "The Waste topic focuses on the management of waste generated by the company's activities. It includes the reduction, reuse, recycling, and proper disposal of waste materials. The company should assess its waste generation and implement measures to minimize waste production. It should also establish procedures for the safe handling and disposal of hazardous waste. The company should disclose its waste management practices, including the types and quantities of waste generated, recycling rates, and any initiatives to reduce waste. Additionally, the company should consider the environmental impacts of its waste management practices, such as air and water pollution, and take steps to mitigate these impacts.",
                        "actions": [
                            "Implement waste reduction and recycling programs",
                            "Adopt sustainable packaging practices",
                            "Monitor and report on waste generation and disposal"
                        ],
                        "disclosures": [
                            {
                                "name": "Given the topic: 'Topic 13.8 Waste' from the sector: 'Based on the provided company information, the relevant GRI Sector Standard cannot be determined as the company sector is not specified. Please provide the industry sector in which the company operates in order to identify the appropriate GRI Sector Standard.",
                                "description": "The relevant GRI Topic Standard for 'Topic 13.8 Waste' cannot be determined without knowing the specific industry sector in which the company operates. Please provide the industry sector information to identify the appropriate GRI Topic Standard."
                            }
                        ]
                    }
                },
                {
                    "topic": {
                        "name": "Topic 13.5 Soil health",
                        "description": "The Soil Health topic focuses on the company's impact on soil quality and fertility. It includes the management of soil erosion, soil contamination, and soil degradation. The company should assess its activities that may affect soil health, such as land use, agricultural practices, and construction activities. It should implement measures to prevent soil erosion, such as erosion control techniques and sustainable land management practices. The company should also monitor and manage soil contamination, including the use of fertilizers, pesticides, and other chemicals. Additionally, the company should disclose its efforts to improve soil health, such as soil conservation programs, soil testing, and soil remediation initiatives.",
                        "actions": [
                            "Implement soil conservation practices",
                            "Use organic fertilizers and natural pest control methods",
                            "Monitor soil quality and implement remediation measures if necessary"
                        ],
                        "disclosures": [
                            {
                                "name": "GRI 103: Management Approach 2016",
                                "description": "This disclosure provides information on how the organization manages soil health and implements practices to improve soil quality."
                            },
                            {
                                "name": "GRI 416: Customer Health and Safety 2016",
                                "description": "This disclosure focuses on the organization's efforts to ensure customer health and safety in relation to soil health, such as providing safe and healthy products."
                            },
                            {
                                "name": "GRI 417: Marketing and Labeling 2016",
                                "description": "This disclosure addresses the organization's marketing and labeling practices related to soil health, including any claims or certifications regarding soil-friendly products or practices."
                            }
                        ]
                    }
                },
                {
                    "topic": {
                        "name": "Topic 13.3 Biodiversity",
                        "description": "The Biodiversity topic focuses on the company's impact on biodiversity and the conservation of ecosystems. It includes the assessment and management of biodiversity risks and opportunities. The company should identify and assess its activities that may have significant impacts on biodiversity, such as land use changes, habitat destruction, and pollution. It should implement measures to minimize negative impacts on biodiversity, such as habitat restoration, conservation programs, and sustainable resource management. The company should also disclose its efforts to protect and enhance biodiversity, including the conservation of endangered species, the establishment of protected areas, and the promotion of biodiversity education and awareness. Additionally, the company should consider the potential impacts of its supply chain on biodiversity and take steps to address these impacts.",
                        "actions": [
                            "Conduct biodiversity assessments and develop conservation plans",
                            "Support habitat restoration and protection initiatives",
                            "Engage in sustainable land use practices to minimize impacts on biodiversity"
                        ],
                        "disclosures": [
                            {
                                "name": "GRI 303: Water 2018",
                                "description": "This disclosure provides information on the organization's water management practices and their impact on biodiversity, including measures to protect water-related ecosystems."
                            },
                            {
                                "name": "GRI 304: Biodiversity 2016",
                                "description": "This disclosure focuses specifically on the organization's efforts to assess and manage its impacts on biodiversity, including conservation measures and engagement with stakeholders."
                            },
                            {
                                "name": "GRI 305: Emissions 2018",
                                "description": "This disclosure addresses the organization's emissions and their impact on biodiversity, including measures to reduce emissions and mitigate their effects on biodiversity."
                            }
                        ]
                    }
                }
            ]
        },
        "social": {
            "explanation": "The social category includes topics related to the company's impact on society and stakeholders. This can include issues such as supply chain traceability, living income and living wage, and freedom of association and collective bargaining. These topics are important for <aaaaaaaaaaaaaaa> as they operate in the <aaaaaaaaaaaaaaa> industry sector. Their supply chain and workforce may be affected by these social issues, and addressing them can contribute to fair and ethical business practices.",
            "topics": [
                {
                    "topic": {
                        "name": "Topic 13.23 Supply chain traceability",
                        "description": "The Supply Chain Traceability topic focuses on the company's ability to trace its products and inputs throughout the supply chain. It includes the identification and management of supply chain risks, such as human rights violations, environmental degradation, and unethical practices. The company should establish systems and processes to track and monitor its supply chain, including the origin of raw materials, the conditions of production, and the transportation and distribution of products. It should also collaborate with suppliers and stakeholders to ensure transparency and accountability in the supply chain. The company should disclose its efforts to promote supply chain traceability, including the implementation of traceability systems, supplier audits, and supplier engagement programs.",
                        "actions": [
                            "Implement systems to track and trace suppliers and ensure transparency",
                            "Conduct audits and assessments to verify compliance with social standards",
                            "Collaborate with suppliers to improve social performance and address issues"
                        ],
                        "disclosures": [
                            {
                                "name": "Based on the provided information, the relevant GRI Sector Standard cannot be determined as the company sector is not specified. Therefore, the relevant GRI Topic Standards for 'Topic 13.23 Supply chain traceability' cannot be identified.",
                                "description": "The relevant GRI Topic Standards for 'Topic 13.23 Supply chain traceability' cannot be determined without knowing the specific industry sector in which the company operates. Please provide the industry sector information to identify the appropriate GRI Topic Standards."
                            }
                        ]
                    }
                },
                {
                    "topic": {
                        "name": "Topic 13.21 Living income and living wage",
                        "description": "The Living Income and Living Wage topic focuses on the company's commitment to providing fair and decent wages to its employees and workers in its supply chain. It includes the assessment and management of wage levels to ensure they meet the basic needs of workers and their families. The company should establish policies and practices that promote living incomes and living wages, including fair wage- setting mechanisms, regular wage reviews, and social dialogue with workers and their representatives. The company should also collaborate with suppliers and stakeholders to promote fair wages throughout the supply chain. Additionally, the company should disclose its efforts to ensure living incomes and living wages, including wage levels, wage gaps, and any initiatives to address wage inequality.",
                        "actions": [
                            "Conduct assessments to determine if workers are receiving fair wages",
                            "Engage in dialogue with stakeholders to address wage disparities",
                            "Implement policies and practices to ensure fair compensation for workers"
                        ],
                        "disclosures": [
                            {
                                "name": "GRI 202: Market Presence 2016",
                                "description": "This disclosure provides information on the organization's market presence and its efforts to ensure fair wages and income for workers, including living wage considerations."
                            },
                            {
                                "name": "GRI 204: Procurement Practices 2016",
                                "description": "This disclosure focuses on the organization's procurement practices and their impact on workers' income, including fair trade and responsible sourcing initiatives."
                            },
                            {
                                "name": "GRI 205: Anti-corruption 2016",
                                "description": "This disclosure addresses the organization's efforts to prevent corruption and bribery, which can have an impact on fair wages and income for workers."
                            }
                        ]
                    }
                },
                {
                    "topic": {
                        "name": "Topic 13.18 Freedom of association and collective bargaining",
                        "description": "The Freedom of Association and Collective Bargaining topic focuses on the company's respect for workers' rights to freedom of association and collective bargaining. It includes the assessment and management of labor relations and the promotion of workers' rights to form and join trade unions, engage in collective bargaining, and participate in workplace decision-making. The company should establish policies and practices that support workers' rights to freedom of association and collective bargaining, including non- discrimination, protection against anti-union practices, and mechanisms for resolving labor disputes. The company should also collaborate with workers and their representatives to ensure meaningful worker participation and representation. Additionally, the company should disclose its efforts to promote freedom of association and collective bargaining, including the existence of trade unions, collective bargaining agreements, and any initiatives to address labor rights violations.",
                        "actions": [
                            "Respect and support workers' rights to form unions and engage in collective bargaining",
                            "Establish mechanisms for workers to voice their concerns and grievances",
                            "Collaborate with labor organizations to improve working conditions and labor rights"
                        ],
                        "disclosures": [
                            {
                                "name": "GRI 402: Labor/Management Relations 2016",
                                "description": "This disclosure provides information on the organization's approach to labor/management relations, including the promotion of freedom of association and collective bargaining rights."
                            },
                            {
                                "name": "GRI 403: Occupational Health and Safety 2018",
                                "description": "This disclosure focuses on the organization's efforts to ensure occupational health and safety, which includes providing a safe and conducive environment for workers to exercise their rights to freedom of association and collective bargaining."
                            },
                            {
                                "name": "GRI 405: Diversity and Equal Opportunity 2016",
                                "description": "This disclosure addresses the organization's commitment to diversity and equal opportunity, which includes respecting and promoting workers' rights to freedom of association and collective bargaining."
                            }
                        ]
                    }
                }
            ]
        },
        "governance": {
            "explanation": "The governance category includes topics related to the company's governance structure and practices. This can include issues such as board composition, executive compensation, and risk management. Good governance is important for <aaaaaaaaaaaaaaa> as it ensures transparency, accountability, and ethical decision-making. By addressing these topics, the company can enhance its reputation and build trust with stakeholders.",
            "topics": []
        },
        "general": {
            "general_compliance": "Based on the provided company information, the relevant GRI Sector Standard cannot be determined as the company sector is not specified. Please provide the industry sector in which the company operates in order to identify the appropriate GRI Sector Standard."
        },
        "rating": [
            {
                "topic": "Environmental",
                "rating": "3"
            },
            {
                "topic": "Social",
                "rating": "4"
            },
            {
                "topic": "Governance",
                "rating": "2"
            }
        ]
    }
)
